# Generated by Django 5.0.2 on 2024-03-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('src', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
    ]
