# Generated by Django 4.0.4 on 2024-02-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_exercice_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='exercice',
            name='choices',
            field=models.ManyToManyField(related_name='choices', to='tech.choice'),
        ),
    ]
