# Generated by Django 4.0.4 on 2024-02-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_choice_exercice_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='choices',
        ),
        migrations.AddField(
            model_name='exercice',
            name='choices',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
